Feature/rna fastq config
UMCUGenetics/rsync_to_rdisc pull request #42
Opened 2024-12-17 11:00 UTC by ellendejong

### What has changed?

- Add include/exclude params to rsync.
- Add transfer settings RAW_data_RNAseq (fastq files RNAseq).
- Change processed data RNA transfer settings

2025-01-14 13:56 UTC, Jorisvansteenbrugge requested changes
I made a few in-depth comments that I think are worth looking at, the rest looks good.

2025-01-14 13:56 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +            rsync_params += " ".join([f" --exclude '{pattern}'" for pattern in transfer_settings["exclude"]])
include and exclude are referred to as `--include=` & `--exclude=` in the rsync manual, but I assume this (i.e., with a space instead of an equal sign) is tested and works as well :)

2025-01-14 13:56 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +        )
I believe it is typically preferred to build a shell command with parameters in a list object rather than by extending a string. This makes it theoretically more secure as it is more difficult to inject unwanted parameters and prevents incorrect shell interpretations. It is also a bit easier to read/maintain, since you can combine them like this in the end:



```{python}
user = "user"
host = "host"
source_path = "/source/path"
source_destination = f"{user}@{host}:{destination_path}"
target_path = "/something/output"

include_patterns = ... # can be empty when not applicable
exclude_patterns = ...# can be empty when not applicable

shell_cmd = [
    "rsync", 
    "-rahuL", 
    "--stats",
    include_patterns,
    exclude_patterns,
    source_destination,
    target_path,
]
```

Something like that!

2025-01-14 13:56 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +        os.system(
Is there a reason `os.system` is used instead of one of the `subprocess` options? I thought subprocess is considered to be more flexible and robust.

2025-01-14 13:56 UTC, Jorisvansteenbrugge commented on settings.py
> +                "input": "/hpc/diaggen/data/upload/Transcriptomes/",
I suppose naming this 'Transcriptomes' is more in-line with how we also label 'Genomes', however, I would argue that Transcriptomes are assemblies of RNA-seq reads rather than mapped RNA-seq reads (which I assume is the case here, but I might be wrong).

2025-01-21 09:45 UTC, ellendejong commented on rsync_to_rdisc.py
> +            rsync_params += " ".join([f" --exclude '{pattern}'" for pattern in transfer_settings["exclude"]])
Appreciate the manual reference! :) Yes, command works without equal sign.

2025-01-21 09:48 UTC, ellendejong commented on rsync_to_rdisc.py
> +        os.system(
No (valid) reason. I extended existing code. `rsync_to_rdisc` has been around for a while. I can change all `os.system` calls to `subprocess`.

2025-01-21 09:49 UTC, ellendejong commented on settings.py
> +                "input": "/hpc/diaggen/data/upload/Transcriptomes/",
Do you have an alternative suggestion that is in-line with 'Genomes' / 'Exomes' ?

2025-01-21 12:53 UTC, Jorisvansteenbrugge commented on settings.py
> +                "input": "/hpc/diaggen/data/upload/Transcriptomes/",
We agreed to leave ‘Transcriptomes’ unchanged for now and will consider this suggestion in a future refactor.

2025-01-21 13:35 UTC, Jorisvansteenbrugge requested changes
Nice work :) I’ve made a few additional suggestions to streamline the subprocess section.

2025-01-21 13:35 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +        subprocess.run(rsync_cmd, shell=True, stdout=subprocess.PIPE, encoding="UTF-8")
A small remark is that this variable is called `parse_stdout`, but it seems to do three different things.

1) it redirects (appends) the **standard output** to a log file
2) It redirects (appends) the **standard error** to a error log file
3) it redirects the **standard error** to a temporary path

None of them is technically 'parsing' anything, like the variable name suggests.

subprocess actually has built-in functions to handle output piping. 

```suggestion
        rsync_cmd = [
            "rsync",
            "-rahuL",
            "--stats",
            source_destination,
            target_path
        ]

        # Using list slicing to extend rsync_cmd list with include / exclude patterns.
        rsync_cmd[3:3] = exclude_patterns
        # Add include patterns before exclude patterns.
        rsync_cmd[3:3] = include_patterns

        with open(settings.log_path, 'w') as out, open(settings.errorlog_path, 'w') as err: # Or replace 'w' with 'a' when appending
            subprocess.run(rsync_cmd, shell=True, stdout=out, stderr=err, encoding="UTF-8")
```

2025-01-21 13:35 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +            include_patterns = ""
To match the variable type when empty/filled
```suggestion
            include_patterns = []
```

2025-01-21 13:35 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +            exclude_patterns = ""
To match the variable type when empty/filled
```suggestion
            exclude_patterns = []
```

2025-01-21 13:35 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +        rsync_cmd[3:3] = include_patterns
Why would you use list slicing to incorporate the exclude and include patterns to the rsync_cmd? To me it seems to make more sense to add them to the rsync_cmd list constructor. 

Considering `exclude_patterns` may look something like this `exclude_pattern = ["--exclude pattern_A", "--exclude pattern_B"]` **or** `exclude_pattern = []` (I changed the empty behaviour to [] in a previous comment). Then the variable can be added immediately to `rsync_cmd`

```suggestion
        rsync_cmd = [
            "rsync",
            "-rahuL",
            "--stats",
            *exclude_pattern, # add the values in the exclude_pattern list, to the rsync_cmd list, or add nothing if exclude_pattern is an empty list
            *include_pattern,
            source_destination,
            target_path,
            parse_stdout
        ]
```

2025-01-21 13:35 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +        subprocess.run(rsync_cmd, shell=True, stdout=subprocess.PIPE, encoding="UTF-8")
Another improvement is to validate the return code of the subprocess command. I didn't add this as a suggestion to avoid suggesting multiple things at once, but you could do:

```
result = subprocess.run(rsync_cmd, shell=True, stdout=out, stderr=err, encoding="UTF-8")
if result.returncode != 0:
    # throw an error or something
```

2025-01-22 09:35 UTC, ellendejong commented on rsync_to_rdisc.py
> +        rsync_cmd[3:3] = include_patterns
Nice!

2025-02-07 09:54 UTC, Jorisvansteenbrugge approved these changes

2025-02-07 09:55 UTC, merged