Release/v3.4.0
UMCUGenetics/rsync_to_rdisc pull request #44
Opened 2024-12-30 10:43 UTC by ellendejong

### What has changed?

### TO DO

- [ ] #42 
- [ ] #39

2025-02-07 14:24 UTC, rernst submitted a review, later dismissed
All reviewed in previous pr's

2025-04-17 07:09 UTC, melferink commented on settings.py
> +                "output": "Illumina/Research_Dx/Transcriptomes/UMCU_hg38/",
Dit lijkt mij niet de juiste folder voor in prodcutie wat het in ten slotte geen research meer na de implementatie toch?
Dan zou ik keizen voor /mnt/bgarray/Illumina/Transcriptomes/ of /mnt/bgarray/Illumina/RNAseq/

2025-04-24 12:35 UTC, rernst commented on settings.py
> +                "output": "Illumina/Research_Dx/Transcriptomes/UMCU_hg38/",
Fixed in [cb74422](https://github.com/UMCUGenetics/rsync_to_rdisc/pull/44/commits/cb74422df324e81080b411c12a4b28cf3d17e778) en [f9697f5](https://github.com/UMCUGenetics/rsync_to_rdisc/pull/44/commits/f9697f542c61d0277aa2015f719537536d6840fd)

2025-04-28 08:25 UTC, Jorisvansteenbrugge requested changes
Looks good over-all, a few small considerations/questions

2025-04-28 08:25 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +# TODO: add docstrings to all functions.
Is there a specific reason why doc strings have not been included in this release?

2025-04-28 08:25 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +def send_mail_lost_mount(mount_name, run_file):
For next time, best practice would be to add new parameters after the existing one (makes it easier to be backwards compatible).

2025-04-28 08:25 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +def is_mount_available(mount_name, mount_path, run_file):
This function might benefit from a small refactor;
is_mount_available() would suggest that the function checks if the mount is available, and then returns either True of False.
Which it does, but it also sends an email if the mount is unavailable, which in my opinion should be placed within the `if __name__ == "__main__":` block, which calls this function. 
In main you already check with an if else statement if the mount is available so placing the send_mail_lost_mount() call in the `else`  makes a lot of sense imo (https://github.com/UMCUGenetics/rsync_to_rdisc/blob/34299f04a85f51ad375ef25723914c84e67e05f0/rsync_to_rdisc.py#L408)

2025-04-28 08:25 UTC, Jorisvansteenbrugge commented on rsync_to_rdisc.py
> +                sys.exit("Connection to HPC transfer nodes are lost.")
I would make the spelling of 'transfernodes/transfer nodes'  consistent within the document (e.g., https://github.com/UMCUGenetics/rsync_to_rdisc/blob/34299f04a85f51ad375ef25723914c84e67e05f0/rsync_to_rdisc.py#L47)

2025-04-28 09:06 UTC, melferink commented on rsync_to_rdisc.py
> +                sys.exit("Connection to HPC transfer nodes are lost.")
agree!

2025-04-28 09:15 UTC, melferink commented on rsync_to_rdisc.py
> +def is_mount_available(mount_name, mount_path, run_file):
Agree

2025-04-29 08:33 UTC, Jorisvansteenbrugge approved these changes
Looks good to me

2025-08-07 10:35 UTC, merged